//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolScheduleEntities3 : DbContext
    {
        public static SchoolScheduleEntities3 _context;
        public SchoolScheduleEntities3()
            : base("name=SchoolScheduleEntities")
        {
        }
        public static SchoolScheduleEntities3 GetContext()
        {
            if (_context == null)
                _context = new SchoolScheduleEntities3();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Class1> Class1 { get; set; }
        public virtual DbSet<LessonTime> LessonTime { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<ScheduleE> ScheduleE { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<TeacherSubject> TeacherSubject { get; set; }
        public virtual DbSet<User1> User1 { get; set; }
    }
}
