//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleE
    {
        public int IDSchedule { get; set; }
        public Nullable<System.DateTime> DayOfTheWeek { get; set; }
        public Nullable<int> LessonTime { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<int> Subject1 { get; set; }
        public Nullable<int> Subject2 { get; set; }
        public Nullable<int> Subject3 { get; set; }
        public Nullable<int> Subject4 { get; set; }
        public Nullable<int> Subject5 { get; set; }
        public Nullable<int> Subject6 { get; set; }
        public Nullable<int> Subject7 { get; set; }
        public Nullable<int> Class1 { get; set; }
    
        public virtual Class1 Class11 { get; set; }
        public virtual LessonTime LessonTime1 { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Subject Subject8 { get; set; }
        public virtual Subject Subject9 { get; set; }
        public virtual Subject Subject10 { get; set; }
        public virtual Subject Subject11 { get; set; }
        public virtual Subject Subject12 { get; set; }
        public virtual Subject Subject13 { get; set; }
    }
}
