//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherSubject
    {
        public int TeacherSubjectID { get; set; }
        public Nullable<int> Subject { get; set; }
        public Nullable<int> Teacher { get; set; }
    
        public virtual Subject Subject1 { get; set; }
        public virtual Teacher Teacher1 { get; set; }
    }
}
